services:
  - type: web
    name: parking-citation-api
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python api_server.py
    # Note: This service ONLY hosts the web application
    # Scraping is handled by GitHub Actions (see .github/workflows/)
    envVars:
      - key: DB_HOST
        value: db.kctfygcpobxjgpivujiy.supabase.co
      - key: DB_NAME
        value: postgres
      - key: DB_USER
        value: postgres
      - key: DB_PORT
        value: "5432"
      - key: DB_PASSWORD
        sync: false # Will be set manually in Render dashboard
      - key: SUPABASE_URL
        value: https://kctfygcpobxjgpivujiy.supabase.co
      - key: SUPABASE_ANON_KEY
        sync: false # Will be set manually in Render dashboard
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false # Will be set manually in Render dashboard - REQUIRED for map access
      - key: EMAIL_HOST
        value: smtp.gmail.com
      - key: EMAIL_PORT
        value: "587"
      - key: EMAIL_USER
        value: ammarat@umich.edu
      - key: EMAIL_PASSWORD
        sync: false # Will be set manually in Render dashboard
      - key: NOTIFICATION_EMAIL
        value: ammarat@umich.edu
      - key: STORAGE_PROVIDER
        value: cloudflare_r2
      - key: R2_ACCESS_KEY_ID
        sync: false # Will be set manually in Render dashboard
      - key: R2_SECRET_ACCESS_KEY
        sync: false # Will be set manually in Render dashboard
      - key: R2_ACCOUNT_ID
        sync: false # Will be set manually in Render dashboard
      - key: R2_BUCKET_NAME
        value: parking-citations
