name: Parking Citation Scraper
on:
  schedule:
    # Run every 10 minutes
    - cron: "*/1 * * * *"
  # Allow manual triggering
  workflow_dispatch:
  # Run on push to main (for testing)
  push:
    branches: [main]

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install Tesseract OCR
        run: |
          sudo apt-get update
          sudo apt-get install -y tesseract-ocr

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run scraper
        run: python scraper_only.py
        env:
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_NAME: ${{ secrets.DB_NAME }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_PORT: ${{ secrets.DB_PORT }}

          # Supabase Configuration
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}

          # Email Configuration
          EMAIL_HOST: ${{ secrets.EMAIL_HOST }}
          EMAIL_PORT: ${{ secrets.EMAIL_PORT }}
          EMAIL_USER: ${{ secrets.EMAIL_USER }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          NOTIFICATION_EMAIL: ${{ secrets.NOTIFICATION_EMAIL }}

          # Storage Configuration
          STORAGE_PROVIDER: ${{ secrets.STORAGE_PROVIDER }}
          R2_ACCESS_KEY_ID: ${{ secrets.R2_ACCESS_KEY_ID }}
          R2_SECRET_ACCESS_KEY: ${{ secrets.R2_SECRET_ACCESS_KEY }}
          R2_ACCOUNT_ID: ${{ secrets.R2_ACCOUNT_ID }}
          R2_BUCKET_NAME: ${{ secrets.R2_BUCKET_NAME }}
          R2_PUBLIC_URL: ${{ secrets.R2_PUBLIC_URL }}

          # Image Compression Settings
          IMAGE_MAX_WIDTH: ${{ secrets.IMAGE_MAX_WIDTH }}
          IMAGE_MAX_HEIGHT: ${{ secrets.IMAGE_MAX_HEIGHT }}
          IMAGE_QUALITY: ${{ secrets.IMAGE_QUALITY }}
          IMAGE_FORMAT: ${{ secrets.IMAGE_FORMAT }}

          # Scraper seeds and range (optional; defaults already work without these)
          # AA_BASE_SEED defaults to last successful citation in DB when unset
          AA_BASE_SEED: ${{ secrets.AA_BASE_SEED }}
          NC_BASE_SEED: "2081673"
          SCRAPE_RANGE_SIZE: "200"
